/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GameRouteImport } from './routes/game'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GameIndexRouteImport } from './routes/game.index'
import { Route as GameWebRouteImport } from './routes/game.web'
import { Route as GameVisionsRouteImport } from './routes/game.visions'
import { Route as GameOracleRouteImport } from './routes/game.oracle'
import { Route as GameHuntRouteImport } from './routes/game.hunt'

const GameRoute = GameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GameIndexRoute = GameIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GameRoute,
} as any)
const GameWebRoute = GameWebRouteImport.update({
  id: '/web',
  path: '/web',
  getParentRoute: () => GameRoute,
} as any)
const GameVisionsRoute = GameVisionsRouteImport.update({
  id: '/visions',
  path: '/visions',
  getParentRoute: () => GameRoute,
} as any)
const GameOracleRoute = GameOracleRouteImport.update({
  id: '/oracle',
  path: '/oracle',
  getParentRoute: () => GameRoute,
} as any)
const GameHuntRoute = GameHuntRouteImport.update({
  id: '/hunt',
  path: '/hunt',
  getParentRoute: () => GameRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/game': typeof GameRouteWithChildren
  '/game/hunt': typeof GameHuntRoute
  '/game/oracle': typeof GameOracleRoute
  '/game/visions': typeof GameVisionsRoute
  '/game/web': typeof GameWebRoute
  '/game/': typeof GameIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/game/hunt': typeof GameHuntRoute
  '/game/oracle': typeof GameOracleRoute
  '/game/visions': typeof GameVisionsRoute
  '/game/web': typeof GameWebRoute
  '/game': typeof GameIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/game': typeof GameRouteWithChildren
  '/game/hunt': typeof GameHuntRoute
  '/game/oracle': typeof GameOracleRoute
  '/game/visions': typeof GameVisionsRoute
  '/game/web': typeof GameWebRoute
  '/game/': typeof GameIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/game'
    | '/game/hunt'
    | '/game/oracle'
    | '/game/visions'
    | '/game/web'
    | '/game/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/game/hunt'
    | '/game/oracle'
    | '/game/visions'
    | '/game/web'
    | '/game'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/game'
    | '/game/hunt'
    | '/game/oracle'
    | '/game/visions'
    | '/game/web'
    | '/game/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  GameRoute: typeof GameRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/game': {
      id: '/game'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof GameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/': {
      id: '/game/'
      path: '/'
      fullPath: '/game/'
      preLoaderRoute: typeof GameIndexRouteImport
      parentRoute: typeof GameRoute
    }
    '/game/web': {
      id: '/game/web'
      path: '/web'
      fullPath: '/game/web'
      preLoaderRoute: typeof GameWebRouteImport
      parentRoute: typeof GameRoute
    }
    '/game/visions': {
      id: '/game/visions'
      path: '/visions'
      fullPath: '/game/visions'
      preLoaderRoute: typeof GameVisionsRouteImport
      parentRoute: typeof GameRoute
    }
    '/game/oracle': {
      id: '/game/oracle'
      path: '/oracle'
      fullPath: '/game/oracle'
      preLoaderRoute: typeof GameOracleRouteImport
      parentRoute: typeof GameRoute
    }
    '/game/hunt': {
      id: '/game/hunt'
      path: '/hunt'
      fullPath: '/game/hunt'
      preLoaderRoute: typeof GameHuntRouteImport
      parentRoute: typeof GameRoute
    }
  }
}

interface GameRouteChildren {
  GameHuntRoute: typeof GameHuntRoute
  GameOracleRoute: typeof GameOracleRoute
  GameVisionsRoute: typeof GameVisionsRoute
  GameWebRoute: typeof GameWebRoute
  GameIndexRoute: typeof GameIndexRoute
}

const GameRouteChildren: GameRouteChildren = {
  GameHuntRoute: GameHuntRoute,
  GameOracleRoute: GameOracleRoute,
  GameVisionsRoute: GameVisionsRoute,
  GameWebRoute: GameWebRoute,
  GameIndexRoute: GameIndexRoute,
}

const GameRouteWithChildren = GameRoute._addFileChildren(GameRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  GameRoute: GameRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
